{"name": "Невозможность получения заказа неавторизованным пользователем", "status": "passed", "steps": [{"name": "Получение заказов пользователя", "status": "passed", "parameters": [{"name": "headers", "value": "None"}], "start": 1749394511459, "stop": 1749394511540}], "start": 1749394511459, "stop": 1749394511540, "uuid": "0d6c5a9a-ae8a-40a6-a4b6-d556c147b6ce", "historyId": "cab85d42ac4083fc6ad372310075f0ab", "testCaseId": "cab85d42ac4083fc6ad372310075f0ab", "fullName": "tests.test_get_orders_user.TestGetUserOrders#test_get_orders_without_authorization_fails_with_401", "labels": [{"name": "feature", "value": "Получение заказов пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders_user"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "DESKTOP-579T290"}, {"name": "thread", "value": "27800-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders_user"}]}